all: 
	rm -f *.o;
	make -f Makefile_namedpipe;
	###rm -f *.o;
	###make -f Makefile_mqtt2;

clean:
	rm -f ../../common/src/*.o;
	rm -f *.o;
	rm -f ../bin/*.x;

depend:
	make -f Makefile_namedpipe depend

