### Want to force EosDevice.o to be rebuilt every time
### to ensure that it gets built with the proper EosClientComms
### (EosClientSocket vs. EosClientSerialPort) comm interface.
all:
	cd src; make -f Makefile_namedpipe all; 

clean:
	cd src; make -f Makefile_namedpipe clean;


depend:
	cd src; make -f Makefile_namedpipe depend;


